# Generated by Django 3.1.7 on 2021-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunds_details',
            name='Overall_Gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mutualfunds_details',
            name='date',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
