# Generated by Django 3.1.7 on 2021-06-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf_details',
            name='Buy_Sell',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etf_details',
            name='Overall_Gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='etf_details',
            name='date',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
