# Generated by Django 3.1.7 on 2021-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_details',
            name='avg_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crypto_details',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
