# Generated by Django 3.1.7 on 2021-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20210602_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_details',
            name='Buy_Sell',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crypto_details',
            name='Overall_Gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crypto_details',
            name='Today_Gain',
            field=models.FloatField(default=0),
        ),
    ]
