# Generated by Django 3.1.7 on 2021-06-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_remove_crypto_details_today_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_details',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
