# Generated by Django 3.1.7 on 2021-06-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_auto_20210605_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_details',
            name='date',
            field=models.CharField(default='Date', max_length=255),
        ),
    ]
