# Generated by Django 3.1.7 on 2021-06-04 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=100)),
                ('avg_price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('invested_amount', models.FloatField(default=0)),
                ('current_price', models.FloatField(default=0)),
                ('current_value', models.FloatField(default=0)),
                ('Today_Gain', models.FloatField(default=0)),
                ('Overall_Gain', models.FloatField(default=0)),
                ('Buy_Sell', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='None', max_length=50, null=True)),
                ('date', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
